### PR TITLE
Add an assert method testing entanglement

### LINKED ISSUE #177: Add an assert method checking entanglement

### PR DESCRIPTION
**Pull request by junnaka51**
In this PR I add a new assert method ` assert_not_entangled()` testing entanglement.
This raises an assertion error when specific qubit(s) are entangled.

## Examples of how to use
```py
In [1]: from quantestpy import QuantestPyCircuit
   ...: from quantestpy.assertion.not_entangled import assert_not_entangled
```

```py
In [2]: # check all qubits, not entangled
   ...: qc = QuantestPyCircuit(3)
   ...: qc.add_gate({"name": "h", "control_qubit": [], "target_qubit": [0],
   ...:             "control_value": [], "parameter": []})
   ...: qc.add_gate({"name": "x", "control_qubit": [], "target_qubit": [1],
   ...:             "control_value": [], "parameter": []})
   ...: assert_not_entangled(circuit=qc)
In [3]:
```
```py
In [3]: # check all qubits, entangled
   ...: qc = QuantestPyCircuit(3)
   ...: qc.add_gate({"name": "h", "control_qubit": [], "target_qubit": [0],
   ...:             "control_value": [], "parameter": []})
   ...: qc.add_gate({"name": "x", "control_qubit": [0], "target_qubit": [1],
   ...:             "control_value": [1], "parameter": []})
   ...: assert_not_entangled(circuit=qc)
---------------------------------------------------------------------------
QuantestPyAssertionError                  Traceback (most recent call last)
Cell In [3], line 7
      3 qc.add_gate({"name": "h", "control_qubit": [], "target_qubit": [0],
      4             "control_value": [], "parameter": []})
      5 qc.add_gate({"name": "x", "control_qubit": [0], "target_qubit": [1],
      6             "control_value": [1], "parameter": []})
----> 7 assert_not_entangled(circuit=qc)

File /mnt/workspace/quantestpy_fork/quantestpy/assertion/not_entangled.py:79, in assert_not_entangled(circuit, qubits, atol, msg)
     77 err_msg = "\n".join(err_msg_list)
     78 msg = ut_test_case._formatMessage(msg, err_msg)
---> 79 raise QuantestPyAssertionError(msg)

QuantestPyAssertionError: qubit 0 is entangled with qubit(s) [1].
qubit 1 is entangled with qubit(s) [0].

In [4]: 
```
```py
In [4]: # check specific qubits, not entangled
   ...: qc = QuantestPyCircuit(4)
   ...: qc.add_gate({"name": "h", "control_qubit": [], "target_qubit": [0],
   ...:             "control_value": [], "parameter": []})
   ...: qc.add_gate({"name": "x", "control_qubit": [0], "target_qubit": [1],
   ...:             "control_value": [1], "parameter": []})
   ...: assert_not_entangled(circuit=qc, qubits=[2, 3])

In [5]: 
```
```py
In [5]: # check specific qubits, entangled
   ...: qc = QuantestPyCircuit(4)
   ...: qc.add_gate({"name": "h", "control_qubit": [], "target_qubit": [0],
   ...:             "control_value": [], "parameter": []})
   ...: qc.add_gate({"name": "x", "control_qubit": [0], "target_qubit": [1],
   ...:             "control_value": [1], "parameter": []})
   ...: qc.add_gate({"name": "x", "control_qubit": [1], "target_qubit": [2],
   ...:              "control_value": [1], "parameter": []})
   ...: assert_not_entangled(circuit=qc, qubits=[2, 3])
---------------------------------------------------------------------------
QuantestPyAssertionError                  Traceback (most recent call last)
Cell In [5], line 9
      5 qc.add_gate({"name": "x", "control_qubit": [0], "target_qubit": [1],
      6             "control_value": [1], "parameter": []})
      7 qc.add_gate({"name": "x", "control_qubit": [1], "target_qubit": [2],
      8              "control_value": [1], "parameter": []})
----> 9 assert_not_entangled(circuit=qc, qubits=[2, 3])

File /mnt/workspace/quantestpy_fork/quantestpy/assertion/not_entangled.py:79, in assert_not_entangled(circuit, qubits, atol, msg)
     77 err_msg = "\n".join(err_msg_list)
     78 msg = ut_test_case._formatMessage(msg, err_msg)
---> 79 raise QuantestPyAssertionError(msg)

QuantestPyAssertionError: qubit 2 is entangled with qubit(s) [0, 1].

In [6]: 
```

### CODE REVIEW

**Comment by mitz1012** [comment]
I tried to merge the previous pull request in GitHub, but the merging is blocked. Could you merge it?

**Comment by junnaka51** [comment]
@mitz1012 
> I tried to merge the previous pull request in GitHub, but the merging is blocked. Could you merge it?

The merging is blocked since this PR is not approved yet. Could you please approve first if there is no problem or comment, then we can merge this PR?

**Comment by mitz1012** [comment]
> @mitz1012
> 
> > I tried to merge the previous pull request in GitHub, but the merging is blocked. Could you merge it?
> 
> The merging is blocked since this PR is not approved yet. Could you please approve first if there is no problem or comment, then we can merge this PR?

sorry for my misunderstanding...

**Review by mitz1012 — CHANGES_REQUESTED** [review]
There can be other entanglement states in the case `len(val_pair_uniq_list) == 3`. Could you change the part "Search for entangled pairs".

**Pull request closed without merging**
