### PR TITLE
Implement control gates in Qiskit

### PR DESCRIPTION
**Pull request by mitz1012**
In addition to Implement control gates in Qiskit, I refreshed `converter` and created test.
There are three remaining task, which will be implemented in future pull requests.
1. An appropriate error should be happen when `converter` gets unknown gates.
2. Since I used qiskit.operator to change/add tests for checking gates, all the test files for gates contain qiskit. Adopting to your convension to divide directories for devide qiskit and un-qiskit, I should have created new test files for the part using qiskit.
3. There remains many gates to be implemented.(See all_gates_in_qiskit.xlsx in Slack.)

### CODE REVIEW

**Comment by junnaka51** [comment]
@mitz1012 
image
It seems that the new tests do not run on Github actions...

**Comment by junnaka51** [comment]
@mitz1012 
What about updating test files testing the converter?
It looks a bit wired that you enhance the test files testing the state vector simulator, despite that the main contribution in this PR is to update the converter `quantestpy/converter/sdk/qiskit.py`...

**Comment by junnaka51** [comment]
@mitz1012 
Please check my previous comment https://github.com/QuantestPy/quantestpy/pull/203#issuecomment-1415082231

**Comment by mitz1012** [comment]
https://github.com/QuantestPy/quantestpy/pull/203#issuecomment-1415082231 is resolved. Check it again please. Thanks in advance!

**Review by junnaka51 — APPROVED** [review]
👍 Thanks!!

**Pull request merged**
